### ISSUE TITLE
This data field needs to be available to collect from data warehouse.

### ISSUE THREAD

**Issue by cyberLaVoy** [dsu-effectiveness/NCAA#7]
https://github.com/dsu-effectiveness/NCAA/blob/b37712d3be1dbe419d7410eae70887f419028c30/inst/sql/student_term_course_section.sql#L28

**Comment by jpfeifer-dsu** [comment]
Added student_extracurricular_activity to the export layer which includes student sports based on a given term.

**Comment by cyberLaVoy** [comment]
Data field added to SQL query.
